-- バッチ 5/6 (500件)
INSERT INTO list_records (
  tenant_id, ad_name, company_name, title,
  representative_name, prefecture, company_email,
  phone_numbers, case_memo, address,
  last_call_result, last_call_count,
  recall_date, recall_time,
  status, source,
  custom_data, created_at
) VALUES
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL);