-- バッチ 6/6 (316件)
INSERT INTO list_records (
  tenant_id, ad_name, company_name, title,
  representative_name, prefecture, company_email,
  phone_numbers, case_memo, address,
  last_call_result, last_call_count,
  recall_date, recall_time,
  status, source,
  custom_data, created_at
) VALUES
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', NULL, NULL, NULL,
   NULL, NULL, NULL,
   '{}'::jsonb, NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{}', NULL),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', '金額表示_ポップ_イラスト20250622～', 'トータルリペア　ホネスト', '代表　住宅リペア',
   '小島清', 'Tokyo', '0zy387350p.395n@ezweb.ne.jp',
   '["819035319057"]', NULL, NULL,
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{"rep_title": "代表　住宅リペア", "total_revenue": "はい", "form_q1": "はい", "form_q2": "いいえ", "form_q3": "いいえ"}', '2026-04-28'),
  ('dde9bea6-a017-49e6-a1b6-88494e1e3b4d', '歯科特化型', '山下設計', '部長',
   'Okano Tkao', '神奈川県', 'gzhuoxiong@gmail.com',
   '["819010395158"]', NULL, '川崎市',
   NULL, NULL,
   NULL, NULL,
   '過去データ（未分類）', 'meta_ads',
   '{"rep_title": "部長"}', '2026-04-28');